services:
    admin.interestUser.interest:
        class: Opositatest\InterestUserBundle\Admin\InterestAdmin
        arguments: [~, Opositatest\InterestUserBundle\Entity\Interest, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "OpositatestInterestUserBundle", label: "Intereses" }
        public: true