<?php

namespace Opositatest\InterestUserBundle\Repository;
use Opositatest\InterestUserBundle\Entity\Interest;

/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllChildren(Interest $interest) {
        $children = array();
        if (count($interest->getChildren()->toArray()) == 0) {
            return array($interest);
        } else {
            foreach($interest->getChildren() as $child) {
                array_merge($children, $this->getAllChildren($interest));
            }
        }
        return $children;
    }
}
